INSERT INTO PRODUCT
VALUES(1, 'test1', 'UKR', 10);

INSERT INTO PRODUCT
VALUES(2, 'test2', 'UKR', 20);

INSERT INTO PRODUCT
VALUES(3, 'test3', 'UKR', 30);

INSERT INTO PRODUCT
VALUES(4, 'test4', 'UKR', 40);

INSERT INTO PRODUCT
VALUES(5, 'test5', 'UKR', 50);

INSERT INTO PRODUCT
VALUES(6, 'test6', 'UKR', 60);

INSERT INTO PRODUCT
VALUES(7, 'test7', 'UKR', 70);

INSERT INTO PRODUCT
VALUES(8, 'test8', 'UKR', 80);

INSERT INTO PRODUCT
VALUES(9, 'test9', 'UKR', 90);

INSERT INTO PRODUCT
VALUES(10, 'test10', 'UKR', 100);